In [6]:
import pandas as pd
pd.set_option('display.max_columns', None)  # Display the full content of each column

In [7]:
df1 = pd.read_csv("../data/DATA EXPORT FROM MATRIX - PACKAGE REPORT.csv")

In [8]:
df2 = pd.read_csv("../data/DATA EXPORT FROM MATRIX - REBATE REPORT.csv")

In [9]:
df1.sample(2)

,Package,Rate Model,Bank,MSRP,Invoice,Formula,Buying,Default Rebates,Nondefault Rebates,Rate Style,MF 12,RP 12,Live 12,MF 24,RP 24,Live 24,MF 27,RP 27,Live 27,MF 30,RP 30,Live 30,MF 33,RP 33,Live 33,MF 36,RP 36,Live 36,MF 39,RP 39,Live 39,MF 42,RP 42,Live 42,MF 48,RP 48,Live 48,Package Id,Bank Id
28,2024 Acura RDX AWD SUV,RDX AWD,Cal Automotive,50895,48418,0.951331,-1800,NaN,NaN,TC2H6RKNW 4dr Wgn A-Spec AWD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0032,69,False,0.0032,69,False,NaN,NaN,NaN,NaN,NaN,NaN,65528,48
54,2024 Acura MDX AWD 7 Passenger,MDX AWD,Cal Automotive,62500,58833,0.941328,0,NaN,NaN,YE1H0RKNW 4dr Wgn Tech A-Spec,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0032,70,False,0.0032,70,False,NaN,NaN,NaN,NaN,NaN,NaN,60825,48

In [10]:
df2.sample(2)

,MatrixPackage,Year,Bank,Code,MatrixRateModel,MatrixRateStyle,EndDate,MatirxRebatesSum,AISRebatesSum,Rebate1,RebateDefault1,MatrixValue1,AISValue1,Rebate2,RebateDefault2,MatrixValue2,AISValue2,Rebate3,RebateDefault3,MatrixValue3,AISValue3,Rebate4,RebateDefault4,MatrixValue4,AISValue4,Rebate5,RebateDefault5,MatrixValue5,AISValue5,Rebate6,RebateDefault6,MatrixValue6,AISValue6,Rebate7,RebateDefault7,MatrixValue7,AISValue7,Rebate8,RebateDefault8,MatrixValue8,AISValue8,Rebate9,RebateDefault9,MatrixValue9,AISValue9,Rebate10,RebateDefault10,MatrixValue10,AISValue10,Rebate11,RebateDefault11,MatrixValue11,AISValue11,Rebate12,RebateDefault12,MatrixValue12,AISValue12
7,2024 Acura Integra Hatchback,2024,Cal Automotive,DE4H6RJW A-SPEC TECH,INTEGRA,DE4H6RJW 5dr HB A-Spec Tech Package AT,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,2025 Acura MDX AWD 7 Passenger,2025,Cal Automotive,YE1H9SKNW A-Spec Advance,MDX AWD,YE1H9SKNW 4dr Wgn A-Spec Advance,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df = pd.merge(df1,df2,on=['Bank'])

In [15]:
df = df[['MatrixPackage', 'Year', 'Code', 'MatrixRateModel', 'MatrixRateStyle','Package', 'Rate Model', 'Bank', 'MSRP', 'Invoice', 'Formula', 'Buying',
       'Default Rebates', 'Nondefault Rebates', 'Rate Style', 'MF 12', 'RP 12',
       'Live 12', 'MF 24', 'RP 24', 'Live 24', 'MF 27', 'RP 27', 'Live 27',
       'MF 30', 'RP 30', 'Live 30', 'MF 33', 'RP 33', 'Live 33', 'MF 36',
       'RP 36', 'Live 36', 'MF 39', 'RP 39', 'Live 39', 'MF 42', 'RP 42',
       'Live 42', 'MF 48', 'RP 48', 'Live 48', 'Package Id', 'Bank Id',
       'EndDate', 'MatirxRebatesSum', 'AISRebatesSum', 'Rebate1',
       'RebateDefault1', 'MatrixValue1', 'AISValue1', 'Rebate2',
       'RebateDefault2', 'MatrixValue2', 'AISValue2', 'Rebate3',
       'RebateDefault3', 'MatrixValue3', 'AISValue3', 'Rebate4',
       'RebateDefault4', 'MatrixValue4', 'AISValue4', 'Rebate5',
       'RebateDefault5', 'MatrixValue5', 'AISValue5', 'Rebate6',
       'RebateDefault6', 'MatrixValue6', 'AISValue6', 'Rebate7',
       'RebateDefault7', 'MatrixValue7', 'AISValue7', 'Rebate8',
       'RebateDefault8', 'MatrixValue8', 'AISValue8', 'Rebate9',
       'RebateDefault9', 'MatrixValue9', 'AISValue9', 'Rebate10',
       'RebateDefault10', 'MatrixValue10', 'AISValue10', 'Rebate11',
       'RebateDefault11', 'MatrixValue11', 'AISValue11', 'Rebate12',
       'RebateDefault12', 'MatrixValue12', 'AISValue12']]

In [17]:
df = df[df.MatrixPackage==df.Package]

In [19]:
df = df[df.MatrixRateModel==df['Rate Model']]

In [28]:
df = df[df['Rate Style']==df.MatrixRateStyle]

In [30]:
df.shape

(21, 95)

In [32]:
df.to_csv("../output/merged_rebate_package_data.csv",index=False)